//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocAn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChocAn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albert Campbell,67 Annamark Drive,Amarillo,TX,79182
        ///Willie Flores,1459 Spenser Trail,Toledo,OH,43666
        ///Joseph Wood,333 Delladonna Way,Winter Haven,FL,33884
        ///Robin Williamson,648 Granby Street,Oklahoma City,OK,73147
        ///Christine Webb,21 Dryden Court,Springfield,VA,22156
        ///Howard Ramirez,23 Rowland Point,Miami Beach,FL,33141
        ///Mary Banks,62 Anzinger Street,Albany,NY,12262
        ///Carolyn Duncan,12 Florence Lane,Fullerton,CA,92640
        ///Doris Hamilton,8911 Transport Junction,Columbus,OH,43210
        ///Doris Kelly,1 Knutson Way,Miami, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeedManagers {
            get {
                return ResourceManager.GetString("SeedManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andrew Hansen,8 Magdeline Street,Homestead,FL,33034
        ///Emily Scott,87 Hallows Avenue,Decatur,IL,62525
        ///Joyce Turner,87 Clemons Place,Erie,PA,16505
        ///Susan Hughes,205 Melvin Lane,Jamaica,NY,11407
        ///Samuel Dean,10 Pleasure Avenue,Valdosta,GA,31605
        ///Philip Fields,3 Shelley Alley,San Diego,CA,92110
        ///Lori Cole,6620 Parkside Parkway,Omaha,NE,68164
        ///Brenda Murphy,6 Gerald Circle,Cincinnati,OH,45999
        ///Diane Johnson,3210 Debra Court,Roanoke,VA,24014
        ///Shirley Welch,2993 Hoepker Road,Austin,TX,78778
        ///Ruby Bowman,90886 Alpi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeedMembers {
            get {
                return ResourceManager.GetString("SeedMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robin Diaz,664 Karstens Pass,Miami,FL,33169
        ///Todd Cole,99 Blaine Court,Portland,OR,97240
        ///Jack Ortiz,861 Melody Pass,Lexington,KY,40581
        ///James Sims,1006 Judy Pass,Phoenix,AZ,85035
        ///Julie James,5776 Del Sol Road,Toledo,OH,43699
        ///Judy Scott,171 Superior Point,Albuquerque,NM,87121
        ///Anthony Bailey,5 Canary Lane,Missoula,MT,59806
        ///Ernest Edwards,710 Talisman Junction,Fort Lauderdale,FL,33336
        ///Joseph Burns,85823 Grim Circle,Houston,TX,77288
        ///Justin Rivera,213 Dixon Alley,Washington,DC,20580
        ///Robert Taylor,774 Nor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeedProviders {
            get {
                return ResourceManager.GetString("SeedProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dietitian Consultation,150.00
        ///Physical Therapy,100.00
        ///Sleep Laboratory Session,390.00
        ///Individual Therapy Session,125.00
        ///Group Therapy Session,45.00
        ///Meditation Class,15.00
        ///Yoga Class,15.00
        ///Personal Trainer Session,25.00.
        /// </summary>
        internal static string SeedServices {
            get {
                return ResourceManager.GetString("SeedServices", resourceCulture);
            }
        }
    }
}
